spring.application.name=shopnow

#database configuration
spring.datasource.url=${DB_URL}?prepareThreshold=0
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Threashold, Prepared Statement Collision
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheSizeMiB=0

# debug sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace
# logging.level.org.springframework.security=DEBUG

# debug rollback
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
logging.level.org.springframework.transaction=DEBUG
# jwt
application.security.jwt.secret-key=${JWT_SECRET_KEY}
# a day
application.security.jwt.expiration=86400000
# 7 days
application.security.jwt.refresh-token.expiration=604800000

# OAuth2 Client Registration
spring.security.oauth2.client.registration.google.client-id=${GG_OAUTH2ID_CLIENT}
spring.security.oauth2.client.registration.google.client-secret=${GG_OAUTH2ID_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.github.client-id=${GIT_OAUTH2ID_CLIENT}
spring.security.oauth2.client.registration.github.client-secret=${GIT_OAUTH2ID_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email,read:user

# Redirect URI to frontend on success (custom property)
application.security.oauth2.redirect-uri=http://localhost:3000/oauth2/redirect

#batching
# 1. Kích hoạt Batching và đặt kích thước gói (thường từ 20-50)
spring.jpa.properties.hibernate.jdbc.batch_size=30

# 2. Sắp xếp các câu lệnh Insert/Update để Hibernate gom nhóm hiệu quả hơn
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# 3. (Tùy chọn) Hiển thị thống kê để kiểm tra batching có hoạt động không
spring.jpa.properties.hibernate.generate_statistics=true