package com.example.shopnow.user.models;

import java.util.Collection;
import java.util.List;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import com.example.shopnow.shared.BaseEntity;
import com.example.shopnow.user.api.AuthenticatedUser;
import jakarta.persistence.*;
import lombok.*;

@Getter
@Setter
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Entity
@Table(name = "users")
public class User extends BaseEntity implements UserDetails, AuthenticatedUser {
    private String name;
    private String email;
    private String password;
    
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    private Role role;

    /**
     * Domain factory for OAuth-provisioned users.
     *
     * <p>Encapsulates the User invariant that an OAuth user is always created
     * with a valid, non-null {@link Role#CUSTOMER} role. The placeholder
     * password is supplied by the caller (the provisioning use case) so the
     * existing behaviour — a CUSTOMER user with a random placeholder password —
     * is preserved exactly; this factory does not alter how email/password/role
     * are persisted.
     *
     * @param email                 the user's email (used as the username)
     * @param name                  the user's display name
     * @param placeholderPassword   a placeholder password generated by the caller
     * @return a new {@link User} with {@code role = CUSTOMER}
     */
    public static User createOAuthCustomer(String email, String name, String placeholderPassword) {
        return User.builder()
                .email(email)
                .name(name)
                .role(Role.CUSTOMER) // invariant: OAuth users are always CUSTOMER
                .password(placeholderPassword)
                .build();
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities(){
        return List.of(new SimpleGrantedAuthority("ROLE_"+role.name()));
    };

    @Override
    public String getPassword(){
        return password;
    };

    @Override
    public String getUsername(){
        return email;
    };

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }

    @Override
    public String getRole() {
        return role.name();
    }
}
