server.port=8086
spring.application.name=shopnow-user-service

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/shopnow_user_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

# Swagger Configuration
springdoc.api-docs.path=/api/users/v3/api-docs
springdoc.swagger-ui.path=/api/users/swagger-ui.html
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/api/users/v3/api-docs
springdoc.swagger-ui.urls[1].name=Product Service
springdoc.swagger-ui.urls[1].url=/api/products/v3/api-docs
springdoc.swagger-ui.urls[2].name=Order Service
springdoc.swagger-ui.urls[2].url=/api/orders/v3/api-docs
springdoc.swagger-ui.urls[3].name=Cart Service
springdoc.swagger-ui.urls[3].url=/api/carts/v3/api-docs
springdoc.swagger-ui.urls[4].name=Payment Service
springdoc.swagger-ui.urls[4].url=/api/payments/v3/api-docs
springdoc.swagger-ui.urls[5].name=Auth Service
springdoc.swagger-ui.urls[5].url=/api/auth/v3/api-docs

server.forward-headers-strategy=framework

